//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 gongzhu.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GONGZHU_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1_LINK                132
#define IDD_DIALOG_GAME                 134
#define IDB_BITMAP1                     136
#define IDB_BITMAP2                     137
#define IDB_BITMAP3                     138
#define IDB_BITMAP4                     139
#define IDB_BITMAP5                     140
#define IDB_BITMAP6                     141
#define IDB_BITMAP7                     142
#define IDB_BITMAP8                     143
#define IDB_BITMAP9                     144
#define IDB_BITMAP10                    145
#define IDB_BITMAP11                    146
#define IDB_BITMAP12                    147
#define IDB_BITMAP13                    148
#define IDB_BITMAP14                    149
#define IDB_BITMAP15                    150
#define IDB_BITMAP16                    151
#define IDB_BITMAP17                    152
#define IDB_BITMAP18                    153
#define IDB_BITMAP19                    154
#define IDB_BITMAP20                    155
#define IDB_BITMAP21                    156
#define IDB_BITMAP22                    157
#define IDB_BITMAP23                    158
#define IDB_BITMAP24                    159
#define IDB_BITMAP25                    160
#define IDB_BITMAP26                    161
#define IDB_BITMAP27                    162
#define IDB_BITMAP28                    163
#define IDB_BITMAP29                    164
#define IDB_BITMAP30                    165
#define IDB_BITMAP31                    166
#define IDB_BITMAP32                    167
#define IDB_BITMAP33                    168
#define IDB_BITMAP34                    169
#define IDB_BITMAP35                    170
#define IDB_BITMAP36                    171
#define IDB_BITMAP37                    172
#define IDB_BITMAP38                    173
#define IDB_BITMAP39                    174
#define IDB_BITMAP40                    175
#define IDB_BITMAP41                    176
#define IDB_BITMAP42                    177
#define IDB_BITMAP43                    178
#define IDB_BITMAP44                    179
#define IDB_BITMAP45                    180
#define IDB_BITMAP46                    181
#define IDB_BITMAP47                    182
#define IDB_BITMAP48                    183
#define IDB_BITMAP49                    184
#define IDB_BITMAP50                    185
#define IDB_BITMAP51                    186
#define IDB_BITMAP52                    187
#define IDB_BITMAP53                    188
#define IDR_WAVE_TRANS                  189
#define IDR_WAVE_PLAY                   190
#define IDR_WAVE_COUNT                  191
#define IDR_WAVE_SHOWDOWN               192
#define IDR_WAVE_WIN                    193
#define IDR_WAVE_LOSE                   194
#define IDR_WAVE_SHEEP                  195
#define IDR_WAVE_GAME                   196
#define IDR_WAVE_PIG                    197
#define IDR_WAVE_PLAYTIP                199
#define IDC_CHECK1_START                1000
#define IDC_EDIT1_START                 1001
#define IDC_STATIC_START                1002
#define IDC_STATIC_LINK                 1004
#define IDC_LIST3_LINK                  1007
#define IDC_BUTTON_ORDER3               1008
#define IDC_EDIT1_IP                    1009
#define IDC_BUTTON_ORDER2               1010
#define IDC_EDIT2                       1010
#define IDC_BUTTON_ORDER4               1011
#define IDC_BUTTON1                     1012
#define IDC_BUTTON1_STARTGAME           1012
#define IDC_BUTTON_CARD4                1012
#define IDC_BUTTON_RULE                 1012
#define IDC_BUTTON_CARD2                1013
#define IDC_BUTTON_CARD3                1014
#define IDC_BUTTON_CARD5                1015
#define IDC_BUTTON_CARD6                1016
#define IDC_BUTTON_CARD7                1017
#define IDC_BUTTON_CARD8                1018
#define IDC_BUTTON_CARD9                1019
#define IDC_BUTTON_CARD10               1020
#define IDC_BUTTON_CARD11               1021
#define IDC_BUTTON_CARD12               1022
#define IDC_BUTTON12                    1023
#define IDC_BUTTON_CARD13               1023
#define IDC_BUTTON_CARD1                1024
#define IDC_STATIC_ORDER_DOWN           1025
#define IDC_STATIC_ORDER_LEFT           1026
#define IDC_STATIC_ORDER_RIGHT          1027
#define IDC_STATIC_ORDER_UP             1028
#define IDC_STATIC_ID_UP                1029
#define IDC_STATIC_ID_LEFT              1030
#define IDC_STATIC_ID_RIGHT             1031
#define IDC_STATIC_ID_DOWN              1032
#define IDC_STATIC_SCORE_UP             1033
#define IDC_STATIC_SCORE_RIGHT          1034
#define IDC_STATIC_SCORE_LEFT           1035
#define IDC_STATIC_SCORE_DOWN           1036
#define IDC_STATIC_GOLD_UP              1037
#define IDC_STATIC_GOLD_RIGHT           1038
#define IDC_STATIC_GOLD_DOWN            1039
#define IDC_STATIC_GOLD_LEFT            1040
#define IDC_STATIC_TIME                 1041
#define IDC_STATIC_TIP                  1043
#define IDC_CHECK_SHEEP                 1044
#define IDC_CHECK_TRANS                 1045
#define IDC_CHECK_HEARTA                1046
#define IDC_CHECK_PIG                   1047
#define IDC_BUTTON_SHOWCARD_DOWN        1048
#define IDC_STATIC_COLLECTION_UP        1049
#define IDC_STATIC_COLLECTION_DOWN      1050
#define IDC_STATIC_COLLECTION_LEFT      1051
#define IDC_STATIC_COLLECTION_RIGHT     1052
#define IDC_BUTTON_SHOWCARD_RIGHT       1053
#define IDC_BUTTON_SHOWCARD_LEFT        1054
#define IDC_BUTTON_SHOWCARD_UP          1055
#define IDC_BUTTON_RESTART              1056
#define IDC_BUTTON_GETIP                1059
#define IDC_CHECK_SOUND                 1060
#define IDC_CHECK1                      1061
#define IDC_CHECK_COM                   1061
#define IDC_STATIC_Com                  1062
#define IDC_BUTTON_RANK                 1064
#define IDC_COMBO_DEGREE                1065
#define IDC_BUTTON_RANK2                1065
#define IDC_BUTTON_GENERATE             1065
#define IDC_BUTTON_PASTE                1066

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
